# This file was automatically generated by SWIG
package smartcard;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package smartcard;
bootstrap smartcard;
var_smartcard_init();
@EXPORT = qw( );
1;
