/*
 * FILE : smartcard_wrap.c
 * 
 * This file was automatically generated by :
 * Simplified Wrapper and Interface Generator (SWIG)
 * Version 1.1 (Patch 5)
 * 
 * Portions Copyright (c) 1995-1998
 * The University of Utah and The Regents of the University of California.
 * Permission is granted to distribute this file in any manner provided
 * this notice remains intact.
 * 
 * Do not make changes to this file--changes will be lost!
 *
 */


#define SWIGCODE
/* Implementation : PERL 5 */

#define SWIGPERL
#define SWIGPERL5
#ifdef __cplusplus
#include <math.h>
#include <stdlib.h>
extern "C" {
#endif
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#undef free
#undef malloc
#include <string.h>
#ifdef __cplusplus
}
#endif
/* Definitions for compiling Perl extensions on a variety of machines */

#if defined(WIN32) || defined(__WIN32__)
#   if defined(_MSC_VER)
#	define SWIGEXPORT(a,b) __declspec(dllexport) a b
#   else
#	if defined(__BORLANDC__)
#	    define SWIGEXPORT(a,b) a _export b
#	else
#	    define SWIGEXPORT(a,b) a b
#	endif
#   endif
#else
#   define SWIGEXPORT(a,b) a b
#endif

#ifdef PERL_OBJECT
#define MAGIC_PPERL  CPerl *pPerl = (CPerl *) this;
#define MAGIC_CAST   (int (CPerl::*)(SV *, MAGIC *))
#define SWIGCLASS_STATIC 
#else
#define MAGIC_PPERL
#define MAGIC_CAST
#define SWIGCLASS_STATIC static
#endif


/*****************************************************************************
 * $Header: /home/beazley/SWIG/SWIG1.1b3/swig_lib/perl5/RCS/perl5ptr.swg,v 1.1 1996/12/26 22:17:29 beazley Exp beazley $
 *
 * perl5ptr.swg
 *
 * This file contains supporting code for the SWIG run-time type checking
 * mechanism.  The following functions are available :
 *
 * SWIG_RegisterMapping(char *origtype, char *newtype, void *(*cast)(void *));
 *
 *      Registers a new type-mapping with the type-checker.  origtype is the
 *      original datatype and newtype is an equivalent type.  cast is optional
 *      pointer to a function to cast pointer values between types (this
 *      is only used to cast pointers from derived classes to base classes in C++)
 *      
 * SWIG_MakePtr(char *buffer, void *ptr, char *typestring);
 *     
 *      Makes a pointer string from a pointer and typestring.  The result is returned
 *      in buffer.
 *
 * char * SWIG_GetPtr(SV *obj, void **ptr, char *type)
 *
 *      Gets a pointer value from a Perl5 scalar value.  If there is a 
 *      type-mismatch, returns a character string to the received type.  
 *      On success, returns NULL.
 *
 *
 * You can remap these functions by making a file called "swigptr.swg" in
 * your the same directory as the interface file you are wrapping.
 *
 * These functions are normally declared static, but this file can be
 * can be used in a multi-module environment by redefining the symbol
 * SWIGSTATIC.
 *
 * $Log: perl5ptr.swg,v $
 * Revision 1.1  1996/12/26 22:17:29  beazley
 * Initial revision
 *
 *****************************************************************************/

#include <stdlib.h>

#ifdef SWIG_GLOBAL
#ifdef __cplusplus
#define SWIGSTATIC extern "C"
#else
#define SWIGSTATIC
#endif
#endif

#ifndef SWIGSTATIC
#define SWIGSTATIC static
#endif

/* These are internal variables.   Should be static */

typedef struct SwigPtrType {
  char               *name;
  int                 len;
  void               *(*cast)(void *);
  struct SwigPtrType *next;
} SwigPtrType;

/* Pointer cache structure */

typedef struct {
  int                 stat;               /* Status (valid) bit             */
  SwigPtrType        *tp;                 /* Pointer to type structure      */
  char                name[256];          /* Given datatype name            */
  char                mapped[256];        /* Equivalent name                */
} SwigCacheType;

static int SwigPtrMax  = 64;           /* Max entries that can be currently held */
static int SwigPtrN    = 0;            /* Current number of entries              */
static int SwigPtrSort = 0;            /* Status flag indicating sort            */
static SwigPtrType *SwigPtrTable = 0;  /* Table containing pointer equivalences  */
static int SwigStart[256];             /* Table containing starting positions    */

/* Cached values */

#define SWIG_CACHESIZE  8
#define SWIG_CACHEMASK  0x7
static SwigCacheType SwigCache[SWIG_CACHESIZE];  
static int SwigCacheIndex = 0;
static int SwigLastCache = 0;

/* Sort comparison function */
static int swigsort(const void *data1, const void *data2) {
	SwigPtrType *d1 = (SwigPtrType *) data1;
	SwigPtrType *d2 = (SwigPtrType *) data2;
	return strcmp(d1->name,d2->name);
}

/* Binary Search function */
static int swigcmp(const void *key, const void *data) {
  char *k = (char *) key;
  SwigPtrType *d = (SwigPtrType *) data;
  return strncmp(k,d->name,d->len);
}

/* Register a new datatype with the type-checker */

#ifndef PERL_OBJECT
SWIGSTATIC 
void SWIG_RegisterMapping(char *origtype, char *newtype, void *(*cast)(void *)) {
#else
SWIGSTATIC
#define SWIG_RegisterMapping(a,b,c) _SWIG_RegisterMapping(pPerl, a,b,c)
void _SWIG_RegisterMapping(CPerl *pPerl, char *origtype, char *newtype, void *(*cast)(void *)) {
#endif

  int i;
  SwigPtrType *t = 0, *t1;

  if (!SwigPtrTable) {     
    SwigPtrTable = (SwigPtrType *) malloc(SwigPtrMax*sizeof(SwigPtrType));
    SwigPtrN = 0;
  }
  if (SwigPtrN >= SwigPtrMax) {
    SwigPtrMax = 2*SwigPtrMax;
    SwigPtrTable = (SwigPtrType *) realloc(SwigPtrTable,SwigPtrMax*sizeof(SwigPtrType));
  }
  for (i = 0; i < SwigPtrN; i++)
    if (strcmp(SwigPtrTable[i].name,origtype) == 0) {
      t = &SwigPtrTable[i];
      break;
    }
  if (!t) {
    t = &SwigPtrTable[SwigPtrN];
    t->name = origtype;
    t->len = strlen(t->name);
    t->cast = 0;
    t->next = 0;
    SwigPtrN++;
  }
  while (t->next) {
    if (strcmp(t->name,newtype) == 0) {
      if (cast) t->cast = cast;
      return;
    }
    t = t->next;
  }
  t1 = (SwigPtrType *) malloc(sizeof(SwigPtrType));
  t1->name = newtype;
  t1->len = strlen(t1->name);
  t1->cast = cast;
  t1->next = 0;
  t->next = t1;
  SwigPtrSort = 0;
}

/* Make a pointer value string */

SWIGSTATIC 
void SWIG_MakePtr(char *_c, const void *_ptr, char *type) {
  static char _hex[16] =
  {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
   'a', 'b', 'c', 'd', 'e', 'f'};
  unsigned long _p, _s;
  char _result[20], *_r;    /* Note : a 64-bit hex number = 16 digits */
  _r = _result;
  _p = (unsigned long) _ptr;
  if (_p > 0) {
    while (_p > 0) {
      _s = _p & 0xf;
      *(_r++) = _hex[_s];
      _p = _p >> 4;
    }
    *_r = '_';
    while (_r >= _result)
      *(_c++) = *(_r--);
  } else {
    strcpy (_c, "NULL");
  }
  if (_ptr)
    strcpy (_c, type);
}

/* Define for backwards compatibility */

#define _swig_make_hex   SWIG_MakePtr 

/* Function for getting a pointer value */

#ifndef PERL_OBJECT
SWIGSTATIC 
char *SWIG_GetPtr(SV *sv, void **ptr, char *_t)
#else
SWIGSTATIC
#define SWIG_GetPtr(a,b,c) _SWIG_GetPtr(pPerl,a,b,c)
char *_SWIG_GetPtr(CPerl *pPerl, SV *sv, void **ptr, char *_t)
#endif
{
  char temp_type[256];
  char *name,*_c;
  int  len,i,start,end;
  IV   tmp;
  SwigPtrType *sp,*tp;
  SwigCacheType *cache;

  /* If magical, apply more magic */

  if (SvGMAGICAL(sv))
    mg_get(sv);

  /* Check to see if this is an object */
  if (sv_isobject(sv)) {
    SV *tsv = (SV*) SvRV(sv);
    if ((SvTYPE(tsv) == SVt_PVHV)) {
      MAGIC *mg;
      if (SvMAGICAL(tsv)) {
	mg = mg_find(tsv,'P');
	if (mg) {
	  SV *rsv = mg->mg_obj;
	  if (sv_isobject(rsv)) {
	    tmp = SvIV((SV*)SvRV(rsv));
	  }
	}
      } else {
	return "Not a valid pointer value";
      }
    } else {
      tmp = SvIV((SV*)SvRV(sv));
    }
    if (!_t) {
      *(ptr) = (void *) tmp;
      return (char *) 0;
    }
  } else if (sv == &sv_undef) {            /* Check for undef */
    *(ptr) = (void *) 0;
    return (char *) 0;
  } else if (SvTYPE(sv) == SVt_RV) {       /* Check for NULL pointer */
    *(ptr) = (void *) 0;
    if (!SvROK(sv)) 
      return (char *) 0;
    else
      return "Not a valid pointer value";
  } else {                                 /* Don't know what it is */
      *(ptr) = (void *) 0;
      return "Not a valid pointer value";
  }
  if (_t) {
    /* Now see if the types match */      

    if (!sv_isa(sv,_t)) {
      _c = HvNAME(SvSTASH(SvRV(sv)));
      if (!SwigPtrSort) {
	qsort((void *) SwigPtrTable, SwigPtrN, sizeof(SwigPtrType), swigsort);  
	for (i = 0; i < 256; i++) {
	  SwigStart[i] = SwigPtrN;
	}
	for (i = SwigPtrN-1; i >= 0; i--) {
	  SwigStart[SwigPtrTable[i].name[0]] = i;
	}
	for (i = 255; i >= 1; i--) {
	  if (SwigStart[i-1] > SwigStart[i])
	    SwigStart[i-1] = SwigStart[i];
	}
	SwigPtrSort = 1;
	for (i = 0; i < SWIG_CACHESIZE; i++)  
	  SwigCache[i].stat = 0;
      }
      /* First check cache for matches.  Uses last cache value as starting point */
      cache = &SwigCache[SwigLastCache];
      for (i = 0; i < SWIG_CACHESIZE; i++) {
	if (cache->stat) {
	  if (strcmp(_t,cache->name) == 0) {
	    if (strcmp(_c,cache->mapped) == 0) {
	      cache->stat++;
	      *ptr = (void *) tmp;
	      if (cache->tp->cast) *ptr = (*(cache->tp->cast))(*ptr);
	      return (char *) 0;
	    }
	  }
	}
	SwigLastCache = (SwigLastCache+1) & SWIG_CACHEMASK;
	if (!SwigLastCache) cache = SwigCache;
	else cache++;
      }

      start = SwigStart[_t[0]];
      end = SwigStart[_t[0]+1];
      sp = &SwigPtrTable[start];
      while (start < end) {
	if (swigcmp(_t,sp) == 0) break;
	sp++;
	start++;
      }
      if (start >= end) sp = 0;
      if (sp) {
	while (swigcmp(_t,sp) == 0) {
	  name = sp->name;
	  len = sp->len;
	  tp = sp->next;
	  while(tp) {
	    if (tp->len >= 255) {
	      return _c;
	    }
	    strcpy(temp_type,tp->name);
	    strncat(temp_type,_t+len,255-tp->len);
	    if (sv_isa(sv,temp_type)) {
	      /* Get pointer value */
	      *ptr = (void *) tmp;
	      if (tp->cast) *ptr = (*(tp->cast))(*ptr);

	      strcpy(SwigCache[SwigCacheIndex].mapped,_c);
	      strcpy(SwigCache[SwigCacheIndex].name,_t);
	      SwigCache[SwigCacheIndex].stat = 1;
	      SwigCache[SwigCacheIndex].tp = tp;
	      SwigCacheIndex = SwigCacheIndex & SWIG_CACHEMASK;
	      return (char *) 0;
	    }
	    tp = tp->next;
	  } 
	  /* Hmmm. Didn't find it this time */
 	  sp++;
	}
      }
      /* Didn't find any sort of match for this data.  
	 Get the pointer value and return the received type */
      *ptr = (void *) tmp;
      return _c;
    } else {
      /* Found a match on the first try.  Return pointer value */
      *ptr = (void *) tmp;
      return (char *) 0;
    }
  } 
  *ptr = (void *) tmp;
  return (char *) 0;
}

/* Compatibility mode */

#define _swig_get_hex  SWIG_GetPtr
/* Magic variable code */
#ifndef PERL_OBJECT
#define swig_create_magic(s,a,b,c) _swig_create_magic(s,a,b,c)
static void _swig_create_magic(SV *sv, char *name, int (*set)(SV *, MAGIC *), int (*get)(SV *,MAGIC *)) {
#else
#define swig_create_magic(s,a,b,c) _swig_create_magic(pPerl,s,a,b,c)
static void _swig_create_magic(CPerl *pPerl, SV *sv, char *name, int (CPerl::*set)(SV *, MAGIC *), int (CPerl::*get)(SV *, MAGIC *)) {
#endif
  MAGIC *mg;
  sv_magic(sv,sv,'U',name,strlen(name));
  mg = mg_find(sv,'U');
  mg->mg_virtual = (MGVTBL *) malloc(sizeof(MGVTBL));
  mg->mg_virtual->svt_get = get;
  mg->mg_virtual->svt_set = set;
  mg->mg_virtual->svt_len = 0;
  mg->mg_virtual->svt_clear = 0;
  mg->mg_virtual->svt_free = 0;
}

#define SWIG_init    boot_smartcard

#define SWIG_name   "smartcard::boot_smartcard"
#define SWIG_varinit "smartcard::var_smartcard_init();"
#ifdef __cplusplus
extern "C"
#endif
#ifndef PERL_OBJECT
SWIGEXPORT(void,boot_smartcard)(CV* cv);
#else
SWIGEXPORT(void,boot_smartcard)(CPerl *, CV *cv);
#endif

#include <stdio.h>
#include "alpar.h"
#include "iso7816.h"
extern int serial_init(const char *);
extern int serial_deinit(int );
extern short alpar_recv(int ,unsigned char *,unsigned char *,unsigned char **,unsigned char *);
extern int alpar_send(int ,unsigned char ,unsigned short ,const unsigned char *);
extern int send_num_mask(int ,char *);
extern int idle_mode_high(int );
extern int idle_mode_low(int );
extern int power_down_mode(int );
extern int power_off(int );
extern int power_up_iso(int ,char *);
extern int power_up_3V(int ,char *);
extern int power_up_5V(int ,char *);
extern int card_command(int ,const char *,int ,char *);
extern int apdu_send(int ,unsigned char ,unsigned char ,unsigned char ,unsigned char ,unsigned char ,int ,const char *);
extern int apdu_recv(int ,unsigned char *,unsigned char *,unsigned char *);
extern int select_file(int ,short );
extern int read_binary(int ,short ,int ,char *);
extern int write_binary(int ,short ,int ,char *);
extern int update_binary(int ,short ,int ,char *);
extern int erase_binary(int );
extern int verify_PIN(int ,char *);
extern int delete_file(int ,short );
extern int invalidate(int );
extern int rehabilitate(int );
extern int create_file_tpef(int ,short ,short ,unsigned char ,unsigned char ,unsigned char ,unsigned char );
#ifdef PERL_OBJECT
#define MAGIC_CLASS _wrap_smartcard_var::
class _wrap_smartcard_var : public CPerl {
public:
#else
#define MAGIC_CLASS
#endif
SWIGCLASS_STATIC int swig_magic_readonly(SV *sv, MAGIC *mg) {
    MAGIC_PPERL
    sv = sv; mg = mg;
    croak("Value is read-only.");
    return 0;
}


#ifdef PERL_OBJECT
};
#endif

XS(_wrap_serial_init) {

    int  _result;
    char * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: serial_init(device);");
    _arg0 = (char *) SvPV(ST(0),na);
    _result = (int )serial_init(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_serial_deinit) {

    int  _result;
    int  _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: serial_deinit(fd);");
    _arg0 = (int )SvIV(ST(0));
    _result = (int )serial_deinit(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_alpar_recv) {

    short  _result;
    int  _arg0;
    unsigned char * _arg1;
    unsigned char * _arg2;
    unsigned char ** _arg3;
    unsigned char * _arg4;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 5) || (items > 5)) 
        croak("Usage: alpar_recv(fd,ack,command,data,lrc);");
    _arg0 = (int )SvIV(ST(0));
    if (SWIG_GetPtr(ST(1),(void **) &_arg1,"unsigned charPtr")) {
        croak("Type error in argument 2 of alpar_recv. Expected unsigned charPtr.");
        XSRETURN(1);
    }
    if (SWIG_GetPtr(ST(2),(void **) &_arg2,"unsigned charPtr")) {
        croak("Type error in argument 3 of alpar_recv. Expected unsigned charPtr.");
        XSRETURN(1);
    }
    if (SWIG_GetPtr(ST(3),(void **) &_arg3,"unsigned charPtrPtr")) {
        croak("Type error in argument 4 of alpar_recv. Expected unsigned charPtrPtr.");
        XSRETURN(1);
    }
    if (SWIG_GetPtr(ST(4),(void **) &_arg4,"unsigned charPtr")) {
        croak("Type error in argument 5 of alpar_recv. Expected unsigned charPtr.");
        XSRETURN(1);
    }
    _result = (short )alpar_recv(_arg0,_arg1,_arg2,_arg3,_arg4);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_alpar_send) {

    int  _result;
    int  _arg0;
    unsigned char  _arg1;
    unsigned short  _arg2;
    unsigned char * _arg3;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 4) || (items > 4)) 
        croak("Usage: alpar_send(fd,command,length,data);");
    _arg0 = (int )SvIV(ST(0));
    _arg1 = (unsigned char )SvIV(ST(1));
    _arg2 = (unsigned short )SvIV(ST(2));
    if (SWIG_GetPtr(ST(3),(void **) &_arg3,"unsigned charPtr")) {
        croak("Type error in argument 4 of alpar_send. Expected unsigned charPtr.");
        XSRETURN(1);
    }
    _result = (int )alpar_send(_arg0,_arg1,_arg2,_arg3);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_send_num_mask) {

    int  _result;
    int  _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: send_num_mask(fd,REFERENCE);");
    _arg0 = (int )SvIV(ST(0));
    _arg1 = (char *) SvPV(ST(1),na);
    _result = (int )send_num_mask(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_idle_mode_high) {

    int  _result;
    int  _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: idle_mode_high(fd);");
    _arg0 = (int )SvIV(ST(0));
    _result = (int )idle_mode_high(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_idle_mode_low) {

    int  _result;
    int  _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: idle_mode_low(fd);");
    _arg0 = (int )SvIV(ST(0));
    _result = (int )idle_mode_low(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_power_down_mode) {

    int  _result;
    int  _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: power_down_mode(fd);");
    _arg0 = (int )SvIV(ST(0));
    _result = (int )power_down_mode(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_power_off) {

    int  _result;
    int  _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: power_off(fd);");
    _arg0 = (int )SvIV(ST(0));
    _result = (int )power_off(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_power_up_iso) {

    int  _result;
    int  _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: power_up_iso(fd,REFERENCE);");
    _arg0 = (int )SvIV(ST(0));
    _arg1 = (char *) SvPV(ST(1),na);
    _result = (int )power_up_iso(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_power_up_3V) {

    int  _result;
    int  _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: power_up_3V(fd,REFERENCE);");
    _arg0 = (int )SvIV(ST(0));
    _arg1 = (char *) SvPV(ST(1),na);
    _result = (int )power_up_3V(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_power_up_5V) {

    int  _result;
    int  _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: power_up_5V(fd,REFERENCE);");
    _arg0 = (int )SvIV(ST(0));
    _arg1 = (char *) SvPV(ST(1),na);
    _result = (int )power_up_5V(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_card_command) {

    int  _result;
    int  _arg0;
    char * _arg1;
    int  _arg2;
    char * _arg3;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 4) || (items > 4)) 
        croak("Usage: card_command(fd,iso_cmd,cmd_len,REFERENCE);");
    _arg0 = (int )SvIV(ST(0));
    _arg1 = (char *) SvPV(ST(1),na);
    _arg2 = (int )SvIV(ST(2));
    _arg3 = (char *) SvPV(ST(3),na);
    _result = (int )card_command(_arg0,_arg1,_arg2,_arg3);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_apdu_send) {

    int  _result;
    int  _arg0;
    unsigned char  _arg1;
    unsigned char  _arg2;
    unsigned char  _arg3;
    unsigned char  _arg4;
    unsigned char  _arg5;
    int  _arg6;
    char * _arg7;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 8) || (items > 8)) 
        croak("Usage: apdu_send(fd,cla,ins,p1,p2,p3,datalen,data);");
    _arg0 = (int )SvIV(ST(0));
    _arg1 = (unsigned char )SvIV(ST(1));
    _arg2 = (unsigned char )SvIV(ST(2));
    _arg3 = (unsigned char )SvIV(ST(3));
    _arg4 = (unsigned char )SvIV(ST(4));
    _arg5 = (unsigned char )SvIV(ST(5));
    _arg6 = (int )SvIV(ST(6));
    _arg7 = (char *) SvPV(ST(7),na);
    _result = (int )apdu_send(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6,_arg7);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_apdu_recv) {

    int  _result;
    int  _arg0;
    unsigned char * _arg1;
    unsigned char * _arg2;
    unsigned char * _arg3;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 4) || (items > 4)) 
        croak("Usage: apdu_recv(fd,OUTPUT,OUTPUT,REFERENCE);");
    _arg0 = (int )SvIV(ST(0));
    if (SWIG_GetPtr(ST(1),(void **) &_arg1,"unsigned charPtr")) {
        croak("Type error in argument 2 of apdu_recv. Expected unsigned charPtr.");
        XSRETURN(1);
    }
    if (SWIG_GetPtr(ST(2),(void **) &_arg2,"unsigned charPtr")) {
        croak("Type error in argument 3 of apdu_recv. Expected unsigned charPtr.");
        XSRETURN(1);
    }
    if (SWIG_GetPtr(ST(3),(void **) &_arg3,"unsigned charPtr")) {
        croak("Type error in argument 4 of apdu_recv. Expected unsigned charPtr.");
        XSRETURN(1);
    }
    _result = (int )apdu_recv(_arg0,_arg1,_arg2,_arg3);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_select_file) {

    int  _result;
    int  _arg0;
    short  _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: select_file(fd,fident);");
    _arg0 = (int )SvIV(ST(0));
    _arg1 = (short )SvIV(ST(1));
    _result = (int )select_file(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_read_binary) {

    int  _result;
    int  _arg0;
    short  _arg1;
    int  _arg2;
    char * _arg3;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 4) || (items > 4)) 
        croak("Usage: read_binary(fd,offset,read_buf_length,REFERENCE);");
    _arg0 = (int )SvIV(ST(0));
    _arg1 = (short )SvIV(ST(1));
    _arg2 = (int )SvIV(ST(2));
    _arg3 = (char *) SvPV(ST(3),na);
    _result = (int )read_binary(_arg0,_arg1,_arg2,_arg3);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_write_binary) {

    int  _result;
    int  _arg0;
    short  _arg1;
    int  _arg2;
    char * _arg3;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 4) || (items > 4)) 
        croak("Usage: write_binary(fd,offset,write_buf_length,REFERENCE);");
    _arg0 = (int )SvIV(ST(0));
    _arg1 = (short )SvIV(ST(1));
    _arg2 = (int )SvIV(ST(2));
    _arg3 = (char *) SvPV(ST(3),na);
    _result = (int )write_binary(_arg0,_arg1,_arg2,_arg3);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_update_binary) {

    int  _result;
    int  _arg0;
    short  _arg1;
    int  _arg2;
    char * _arg3;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 4) || (items > 4)) 
        croak("Usage: update_binary(fd,offset,write_buf_length,REFERENCE);");
    _arg0 = (int )SvIV(ST(0));
    _arg1 = (short )SvIV(ST(1));
    _arg2 = (int )SvIV(ST(2));
    _arg3 = (char *) SvPV(ST(3),na);
    _result = (int )update_binary(_arg0,_arg1,_arg2,_arg3);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_erase_binary) {

    int  _result;
    int  _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: erase_binary(fd);");
    _arg0 = (int )SvIV(ST(0));
    _result = (int )erase_binary(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_verify_PIN) {

    int  _result;
    int  _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: verify_PIN(fd,REFERENCE);");
    _arg0 = (int )SvIV(ST(0));
    _arg1 = (char *) SvPV(ST(1),na);
    _result = (int )verify_PIN(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_delete_file) {

    int  _result;
    int  _arg0;
    short  _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: delete_file(fd,fident);");
    _arg0 = (int )SvIV(ST(0));
    _arg1 = (short )SvIV(ST(1));
    _result = (int )delete_file(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_invalidate) {

    int  _result;
    int  _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: invalidate(fd);");
    _arg0 = (int )SvIV(ST(0));
    _result = (int )invalidate(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_rehabilitate) {

    int  _result;
    int  _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: rehabilitate(fd);");
    _arg0 = (int )SvIV(ST(0));
    _result = (int )rehabilitate(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_create_file_tpef) {

    int  _result;
    int  _arg0;
    short  _arg1;
    short  _arg2;
    unsigned char  _arg3;
    unsigned char  _arg4;
    unsigned char  _arg5;
    unsigned char  _arg6;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 7) || (items > 7)) 
        croak("Usage: create_file_tpef(fd,fident,size,ac1,ac2,kn1,kn2);");
    _arg0 = (int )SvIV(ST(0));
    _arg1 = (short )SvIV(ST(1));
    _arg2 = (short )SvIV(ST(2));
    _arg3 = (unsigned char )SvIV(ST(3));
    _arg4 = (unsigned char )SvIV(ST(4));
    _arg5 = (unsigned char )SvIV(ST(5));
    _arg6 = (unsigned char )SvIV(ST(6));
    _result = (int )create_file_tpef(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_perl5_smartcard_var_init) {
    dXSARGS;
    SV *sv;
    cv = cv; items = items;
    XSRETURN(1);
}
#ifdef __cplusplus
extern "C"
#endif
XS(boot_smartcard) {
	 dXSARGS;
	 char *file = __FILE__;
	 cv = cv; items = items;
	 newXS("smartcard::var_smartcard_init", _wrap_perl5_smartcard_var_init, file);
	 newXS("smartcard::serial_init", _wrap_serial_init, file);
	 newXS("smartcard::serial_deinit", _wrap_serial_deinit, file);
	 newXS("smartcard::alpar_recv", _wrap_alpar_recv, file);
	 newXS("smartcard::alpar_send", _wrap_alpar_send, file);
	 newXS("smartcard::send_num_mask", _wrap_send_num_mask, file);
	 newXS("smartcard::idle_mode_high", _wrap_idle_mode_high, file);
	 newXS("smartcard::idle_mode_low", _wrap_idle_mode_low, file);
	 newXS("smartcard::power_down_mode", _wrap_power_down_mode, file);
	 newXS("smartcard::power_off", _wrap_power_off, file);
	 newXS("smartcard::power_up_iso", _wrap_power_up_iso, file);
	 newXS("smartcard::power_up_3V", _wrap_power_up_3V, file);
	 newXS("smartcard::power_up_5V", _wrap_power_up_5V, file);
	 newXS("smartcard::card_command", _wrap_card_command, file);
	 newXS("smartcard::apdu_send", _wrap_apdu_send, file);
	 newXS("smartcard::apdu_recv", _wrap_apdu_recv, file);
	 newXS("smartcard::select_file", _wrap_select_file, file);
	 newXS("smartcard::read_binary", _wrap_read_binary, file);
	 newXS("smartcard::write_binary", _wrap_write_binary, file);
	 newXS("smartcard::update_binary", _wrap_update_binary, file);
	 newXS("smartcard::erase_binary", _wrap_erase_binary, file);
	 newXS("smartcard::verify_PIN", _wrap_verify_PIN, file);
	 newXS("smartcard::delete_file", _wrap_delete_file, file);
	 newXS("smartcard::invalidate", _wrap_invalidate, file);
	 newXS("smartcard::rehabilitate", _wrap_rehabilitate, file);
	 newXS("smartcard::create_file_tpef", _wrap_create_file_tpef, file);
/*
 * These are the pointer type-equivalency mappings. 
 * (Used by the SWIG pointer type-checker).
 */
	 SWIG_RegisterMapping("unsigned short","short",0);
	 SWIG_RegisterMapping("long","unsigned long",0);
	 SWIG_RegisterMapping("long","signed long",0);
	 SWIG_RegisterMapping("signed short","short",0);
	 SWIG_RegisterMapping("signed int","int",0);
	 SWIG_RegisterMapping("short","unsigned short",0);
	 SWIG_RegisterMapping("short","signed short",0);
	 SWIG_RegisterMapping("unsigned long","long",0);
	 SWIG_RegisterMapping("int","unsigned int",0);
	 SWIG_RegisterMapping("int","signed int",0);
	 SWIG_RegisterMapping("unsigned int","int",0);
	 SWIG_RegisterMapping("signed long","long",0);
	 ST(0) = &sv_yes;
	 XSRETURN(1);
}
